server:
  port: 8200

logging.level:
  org.hibernate:
    SQL: TRACE
    type: TRACE

spring:
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  mail:
    default-encoding: UTF-8
    username: ENC(CrxOTC9LBM1QZToWWwAJ9/rLkjoQJWHy6cAFw8GzzZA=)
    password: ENC(7JF1NDvYVd643SXcwHIAS/JCurXzI3xmEXjziXfl2+U=)
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true

  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    bean: jasyptEncryptor
    iv-generator-classname: org.jasypt.iv.NoIvGenerator